### ISSUE TITLE
NPE when @group-content points to a file that doesn't exist

### ISSUE THREAD

**Issue by no-stack-dub-sack** [no-stack-dub-sack/ApexDoc2#4]
@nginth re-opening the [original issue](https://github.com/SalesforceFoundation/ApexDoc/pull/64) here for better tracking

**Comment by no-stack-dub-sack** [comment]
Hey @nginth, just checking on this. I'm almost done with fixing a few other bugs I wanted to get to before posting the first 'release', and this one is definitely one of them :-) Happy to make the fix and credit if for some reason you're not able to fit it in. Let me know!

**Comment by nginth** [comment]
Hi, I apologize, I got very busy all of a sudden. I don’t have the time right now so go ahead and make the fix!

**Comment by no-stack-dub-sack** [comment]
@nginth No prob, thanks!
